version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  build-ios:
    macos:
      xcode: "9.0"
    working_directory: ~/project/ios
    environment:
      FL_OUTPUT_DIR: ~/project/output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      # Not using a workspace here as Node and Yarn versions
      # differ between the macOS image and the Docker containers above.
      - run: cd .. && yarn && cd ios
      - restore_cache:
          key: v2-bundle-{{ checksum "~/project/Gemfile.lock" }}
      - run: bundle install --gemfile ~/project/Gemfile --path ~/project/vendor/bundle
      - run: sudo gem install fastlane
      - save_cache:
          key: v2-bundle-{{ checksum "~/project/Gemfile.lock" }}
          paths: 
            - ~/project/vendor/bundle
      - restore_cache:
          key: pods-{{ checksum "Podfile" }}
      - run: bundle exec pod install
      - save_cache:
          key: pods-{{ checksum "Podfile" }}
          paths: 
            - ~/project/ios/Pods
      - run: bundle exec fastlane beta

  build-android:
    working_directory: ~/project/android
    docker:
      - image: circleci/android:api-25-node8-alpha
    steps:
      - checkout:
          path: ~/project
      # - attach_workspace:
      #     at: ~/project
      - run: cd .. && yarn && cd android
      # - restore_cache:
      #     key: v1-bundle-{{ checksum "~/project/Gemfile.lock" }}
      - run: bundle install --gemfile ~/project/Gemfile --path ~/project/vendor/bundle
      - run: gem install fastlane -NV
      # - save_cache:
      #     key: v1-bundle-{{ checksum "~/project/Gemfile.lock" }}
      #     paths: 
      #       - ~/project/vendor/bundle
      - run: cd ~/project && mkdir -p android/app/src/main/assets && yarn copyAndroidBundle && cd android
      - run: export TERM=xterm && ./gradlew clean assembleRelease -p . --no-daemon --max-workers 2
      - run: bundle exec fastlane beta2

  build-web:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run: yarn
      - run:
          name: Deploy web
          command: yarn build && yarn firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build-react-native:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
            tags:
              ignore: /^v.*/
      - build-ios:
          requires:            
            - build
          filters:
            branches:
              only: master
      - build-android:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - build-web:
          requires:
            - build
          filters:
            branches:
              only: 
                - master